#' Read data pasted from R printing into a data frame
#'
#' `read.so` and `read_so` read data copied from R print methods into a
#' data.frame or tibble, respectively.
#'
#' `read.so` is designed to read the print method of a data.frame back into R,
#' provided there are no unquoted spaces within the printing. `read_so` will
#' read the results of printing a data.frame as well, but will return a tibble.
#' Its more significant feature is that it will read in the results of printing
#' a tibble, with or without the "A tibble", type, and additional row and
#' column metadata lines.
#'
#' The `file` parameter will accept a filepath or connection, but given that
#' these functions are built for interactive use, they are built to accept a
#' single string containing the data (distinguished from a filepath by the
#' presence of a newline) or a vector of lines, as may be generated by
#' [clipr::read_clip()].
#'
#' @param file A path to a file, a connection, or literal data (either a single
#'     string or a vector of lines). If unspecified, reads from the clipboard.
#' @param header Logical.
#' @param stringsAsFactors A logical value indicating whether to convert string
#'     columns to factors. Passed along to [read.table()].
#' @param row_names A logical value indicating whether the input contains a
#'     column of row names. Row names are removed by `read_so`; to keep them,
#'     use `read.so`. For row names with spaces, try [readr::read_table()] or
#'     [readr::read_fwf()].
#' @param ... Passed along to [read.table()] or [readr::read_table2()] by
#'     `read.so` and `read_so`, respectively. Applied after tibble formatting
#'     lines have been removed.
#'
#' @return For `read.so` a data.frame; for `read_so`, a tibble.
#'
#' @export
read.so <- function(file = clipr::read_clip(),
                    header = TRUE, stringsAsFactors = FALSE, ...){
    if (length(file) > 1) {
        file <- paste(file, collapse = '\n')
    }

    if (grepl('\n', file)) {
        utils::read.table(text = file, header = header,
                          stringsAsFactors = stringsAsFactors, ...)
    } else {
        utils::read.table(file, header = header,
                          stringsAsFactors = stringsAsFactors, ...)
    }
}

#' @rdname read.so
#' @export
read_so <- function(file = clipr::read_clip(), row_names = TRUE, ...){
    if (length(file) == 1) {
        file <- readr::read_lines(file)
    }
    file <- file[!grepl('(^\\s*\\*?\\s*(<\\w+>\\s*)+$)|(^\\s*#)', file)]
    if (row_names) {
        file[-1] <- gsub('^\\s*\\S+\\s+', '', file[-1])
    }
    file <- paste0(paste(trimws(file), collapse = '\n'), '\n')
    readr::read_table2(file, ...)
}
